
/**
 * @file AuraGroove Ambient Music Worker
 *
 * This worker operates on a microservice-style architecture.
 * It is the "Sound Engine", responsible for both composing and rendering audio.
 */
import type { DrumNote, SynthNote, WorkerCommand, WorkerSettings, DrumSampleName, InstrumentSettings, ScoreName } from '@/types/music';

// --- 1. PatternProvider (The Music Sheet Library) ---
const PatternProvider = {
    drumPatterns: {
        ambient_beat: [
            { sample: 'kick' as DrumSampleName, time: 0, velocity: 1.0 },
            { sample: 'hat' as DrumSampleName, time: 0.5, velocity: 0.3 },
            { sample: 'snare' as DrumSampleName, time: 1.0, velocity: 0.8 },
            { sample: 'hat' as DrumSampleName, time: 1.5, velocity: 0.3 },
            { sample: 'kick' as DrumSampleName, time: 2.0, velocity: 0.9 },
            { sample: 'hat' as DrumSampleName, time: 2.5, velocity: 0.3 },
            { sample: 'snare' as DrumSampleName, time: 3.0, velocity: 0.7 },
            { sample: 'hat' as DrumSampleName, time: 3.5, velocity: 0.3 },
        ],
        composer: [], // This will be dynamically generated by the EvolutionEngine
        none: []
    },
    getDrumPattern(name: string): DrumNote[] {
        return this.drumPatterns[name as keyof typeof this.drumPatterns] || [];
    },
};

// --- 2. Instrument Generators (The Composers) ---
class DrumGenerator {
    static createScore(patternName: string, barNumber: number, settings: { volume: number }): DrumNote[] {
        if (patternName === 'none') return [];
        const pattern = PatternProvider.getDrumPattern(patternName);
        let score = [...pattern];

        // Add a crash cymbal on the first beat of every 4th bar for ambient_beat
        if (patternName === 'ambient_beat' && barNumber % 4 === 0) {
            score = score.filter(note => note.time !== 0);
            score.push({ sample: 'crash', time: 0, velocity: 0.8 });
        }
        
        return score.map(note => ({...note, velocity: note.velocity * settings.volume}));
    }
}

class EvolutionEngine {
    generateDrumScore(bar: number, settings: {volume: number}): DrumNote[] {
         if (bar % 2 === 0) {
            return [
                { sample: 'kick', time: 0, velocity: 1.0 * settings.volume },
                { sample: 'hat', time: 1, velocity: 0.4 * settings.volume },
                { sample: 'snare', time: 2, velocity: 0.8 * settings.volume },
                { sample: 'hat', time: 3, velocity: 0.4 * settings.volume },
            ];
         }
         return [
                { sample: 'kick', time: 0, velocity: 1.0 * settings.volume },
                { sample: 'hat', time: 1.5, velocity: 0.3 * settings.volume },
                { sample: 'kick', time: 2, velocity: 0.9 * settings.volume },
                { sample: 'snare', time: 3, velocity: 0.7 * settings.volume },
         ]
    }
    
    // --- "Реактивный" аккомпанемент ---
    generateAccompanimentScore(bar: number, settings: WorkerSettings, noteDensity: number): SynthNote[] {
        const instrumentName = settings.instrumentSettings?.accompaniment?.name;
        if (instrumentName === 'none') {
            return [];
        }

        const volume = settings.instrumentSettings?.accompaniment?.volume ?? 0.7;
        const notes = ['C4', 'E4', 'G4']; 
        const score: SynthNote[] = [];

        // Если плотность нот низкая (т.е. мало играют другие инструменты), играем полный аккорд
        if (noteDensity < 2) {
             notes.forEach((note, index) => {
                score.push({
                    note: note,
                    duration: 2, 
                    time: index * 0.02, // Микросдвиг
                    velocity: 0.6 * volume,
                });
            });
        } else {
            // Если другие играют активно, играем легкое арпеджио
            const arpPattern = [0, 1, 2, 1]; // Простой паттерн арпеджио
             arpPattern.forEach((noteIndex, beat) => {
                score.push({
                    note: notes[noteIndex],
                    duration: 0.5,
                    time: beat, // Играем на каждую долю
                    velocity: 0.5 * volume
                });
            });
        }

        return score;
    }

    generateSoloScore(bar: number, settings: WorkerSettings): SynthNote[] {
        const instrumentName = settings.instrumentSettings?.solo?.name;
        if (instrumentName === 'none') {
            return [];
        }
         const volume = settings.instrumentSettings?.solo?.volume ?? 0.8;
         // Простая логика для примера
         if (bar % 4 === 2) {
            return [{
                note: 'B4',
                duration: 1,
                time: 0,
                velocity: 0.8 * volume
            }];
         }
         return [];
    }
    
    generateBassScore(bar: number, settings: WorkerSettings): SynthNote[] {
        const instrumentName = settings.instrumentSettings?.bass?.name;
        if (instrumentName === 'none') {
            return [];
        }
        const volume = settings.instrumentSettings?.bass?.volume ?? 0.9;
        // Простая басовая нота в начале такта
        return [{
            note: 'C2',
            duration: 4,
            time: 0,
            velocity: 1.0 * volume
        }];
    }
}

// Dummy classes for parts that are not yet fully implemented, to avoid breaking changes.
class OmegaScoreGenerator {
    generateScore(bar: number, settings: any) { return []; }
}
class PromenadeScoreGenerator {
     generateScore(bar: number, settings: any) { return []; }
}

// --- 3. Scheduler (The Conductor) ---
// This is now simplified as it doesn't handle rendering or timing, just data generation.
const Scheduler = {
    barCount: 0,
    
    settings: {
        bpm: 75,
        score: 'evolve' as ScoreName,
        drumSettings: { pattern: 'ambient_beat', volume: 0.7, enabled: true },
        instrumentSettings: { 
            solo: { name: "none", volume: 0.8 },
            accompaniment: { name: "synthesizer", volume: 0.7 },
            bass: { name: "none", volume: 0.9 },
        },
    } as WorkerSettings,

    evolutionEngine: new EvolutionEngine(),
    omegaEngine: new OmegaScoreGenerator(),
    promenadeEngine: new PromenadeScoreGenerator(),


    // Calculated properties
    get beatsPerBar() { return 4; },
    get secondsPerBeat() { return 60 / this.settings.bpm; },
    get barDuration() { return this.beatsPerBar * this.secondsPerBeat; },

    init() {
      this.barCount = 0;
      self.postMessage({ type: 'started' });
    },
    
    updateSettings(newSettings: Partial<WorkerSettings>) {
        if (newSettings.drumSettings) this.settings.drumSettings = { ...this.settings.drumSettings, ...newSettings.drumSettings };
        if (newSettings.instrumentSettings) this.settings.instrumentSettings = { ...this.settings.instrumentSettings, ...newSettings.instrumentSettings };
        if (newSettings.bpm) this.settings.bpm = newSettings.bpm;
        if (newSettings.score) this.settings.score = newSettings.score;
    },

    tick() {
        let drumScore: DrumNote[] = [];
        let soloScore: SynthNote[] = [];
        let accompanimentScore: SynthNote[] = [];
        let bassScore: SynthNote[] = [];

        if (this.settings.drumSettings.enabled) {
             if (this.settings.drumSettings.pattern === 'composer') {
                drumScore = this.evolutionEngine.generateDrumScore(this.barCount, this.settings.drumSettings);
            } else {
                 drumScore = DrumGenerator.createScore(this.settings.drumSettings.pattern, this.barCount, this.settings.drumSettings);
            }
        }
        
        // --- Логика реактивного аккомпанемента ---
        // 1. Сначала генерируем соло и бас, чтобы узнать их плотность
        soloScore = this.evolutionEngine.generateSoloScore(this.barCount, this.settings);
        bassScore = this.evolutionEngine.generateBassScore(this.barCount, this.settings);

        // 2. Считаем плотность нот
        const noteDensity = soloScore.length + bassScore.length;
        
        // 3. Генерируем аккомпанемент, передавая ему плотность
        switch(this.settings.score) {
            case 'evolve':
                accompanimentScore = this.evolutionEngine.generateAccompanimentScore(this.barCount, this.settings, noteDensity);
                break;
            case 'omega':
                break;
            case 'promenade':
                break;
        }

        const messageData = {
            drumScore,
            soloScore,
            accompanimentScore,
            bassScore,
            barDuration: this.barDuration,
        };
        
        self.postMessage({ type: 'score', data: messageData });
        
        this.barCount++;
    }
};


// --- MessageBus (The entry point) ---
self.onmessage = async (event: MessageEvent<WorkerCommand>) => {
    const { command, data } = event.data;

    try {
        switch (command) {
            case 'init':
                Scheduler.init();
                break;
            case 'tick':
                 Scheduler.tick();
                 break;
            case 'update_settings':
                 Scheduler.updateSettings(data);
                break;
            // 'start' and 'stop' commands are no longer needed here as timing is controlled by the main thread.
        }
    } catch (e) {
        self.postMessage({ type: 'error', error: e instanceof Error ? e.message : String(e) });
    }
};
