
export const dictionary = {
  auraGroove: {
    title: 'AuraGroove',
    play: 'Play',
    stop: 'Stop',
    composition: 'Composition',
    instruments: 'Instruments',
    samples: 'Samples',
    style: 'Style',
    bpm: 'BPM',
    density: 'Density',
    sleepTimer: 'Sleep Timer',
    minutes: 'Minutes',
    startTimer: 'Start Timer',
    stopTimer: (time: string) => `Stop Timer (${time})`,
    volume: 'Volume',
    part: {
      bass: 'Bass',
      melody: 'Melody',
      accompaniment: 'Accompaniment',
    },
    bassTechnique: 'Technique',
    instrumentName: {
      none: 'None',
      classicBass: 'Classic Bass',
      glideBass: 'Glide Bass',
      ambientDrone: 'Ambient Drone',
      resonantGliss: 'Resonant Gliss',
      hypnoticDrone: 'Hypnotic Drone',
      livingRiff: 'Living Riff',
      cello: 'Cello',
      synth: 'Synth',
      organ: 'Organ',
      mellotron: 'Mellotron',
      theremin: 'Theremin',
      flute: 'Flute',
      lute: 'Lute',
    },
    bassTechniqueName: {
      arpeggio: 'Arpeggio',
      portamento: 'Portamento',
      glissando: 'Glissando',
      glide: 'Glide',
      pulse: 'Pulse',
    },
    sampledTextures: 'Sampled Textures',
    sparkles: 'Sparkles',
    pads: 'Pads',
    drums: 'Drums',
    drumPattern: {
      none: 'None',
      ambient_beat: 'Ambient',
      composer: 'Composer',
    },
    footer: {
      home: 'Home',
      presets: 'Save/Load Presets',
      visualizer: 'Open Visualizer',
      eq: 'EQ',
      help: 'Help',
    },
    presetsModal: {
      title: 'Global Presets',
      description: 'Load a saved preset or save your current settings.',
      loadPlaceholder: 'Load a preset...',
      saveButton: 'Save Current Settings',
      presetSaved: 'Preset Saved',
      presetLoaded: 'Preset Loaded',
      presetSaveError: 'Cannot overwrite the default sample preset.',
      presetSavePrompt: 'Enter a name for your preset:',
      saveError: 'Could not save presets.',
    },
    eqModal: {
      title: 'System Equalizer',
      presetPlaceholder: 'Select a preset',
      presets: {
        mobile: 'Mobile Phones',
        acoustic: 'Acoustic System',
      },
    },
    helpModal: {
      title: 'User Guide',
    },
    scoreName: {
        dreamtales: 'Dreamtales',
        evolve: 'Evolve',
        omega: 'Omega',
        journey: 'Journey',
        multeity: 'Multeity',
        slow_blues: 'Slow Blues',
        celtic_ballad: 'Celtic Ballad',
    },
    toasts: {
        workerError: 'Worker Error',
        audioInitError: 'Audio Initialization Error',
        audioInitErrorDescription: (message: string) => `Could not start audio: ${message}`,
        presetSavedDescription: (name: string) => `"${name}" has been saved.`,
        presetLoadedDescription: (name: string) => `"${name}" has been loaded.`,
    }
  },
  home: {
    title: 'Welcome to AuraGroove',
    description: 'Your personal pure digital ambient music generator.',
    initializing: 'Initializing...',
    enter: 'Enter',
    start: 'Start AuraGroove',
    infoInitializing: 'Please wait, the audio engine is initializing...',
    infoReady: 'Audio engine is ready.',
    infoNotReady: 'Click the button below to initialize the audio engine.',
    footer: (link: string) => `AuraGroove (c) 2025 Evgeniy Somov, ${link}`,
    studio: 'polyankastudio.ru',
  },
  userGuide: {
    whatIsThis: {
      title: "What is this application?",
      content: "This is a unique software composer designed to generate endless, non-repeating background music. It serves to create the perfect sound atmosphere in a wide variety of spaces, from commercial establishments to personal use."
    },
    forWhom: {
      title: "Who is this application for?",
      intro: "The application is ideal for anyone who needs high-quality, unique background music that does not require royalty payments. The main areas of application are:",
      uses: {
        yoga: { title: "Yoga and meditation studios:", description: "Creating a calm and peaceful atmosphere for practices." },
        bars: { title: "Bars and coffee shops:", description: "Unobtrusive, stylish music that does not distract guests." },
        spa: { title: "Massage and SPA salons:", description: "Deeply relaxing melodies for full client immersion in procedures." },
        fitness: { title: "Fitness centers:", description: "Rhythmic and motivating music for workouts." },
        personal: { title: "Personal use:", description: "For concentration during work, study, or simply for relaxation." }
      }
    },
    features: {
      title: "Key Features",
      unique: { title: "Absolutely unique music:", description: "Every melody generated by the application is unique. You will never hear two identical compositions." },
      royaltyFree: { title: "No royalties required:", description: "All created music can be freely used for commercial and personal purposes." },
      endless: { title: "Endless generation:", description: "The music stream can go on forever, constantly evolving and never repeating." }
    },
    howItWorks: {
      title: "How it works? (Technology)",
      importantNote: { title: "Important:", description: "This is not an AI generator in the usual sense. The application's operation is not based on neural networks trained on other people's music, but on pure mathematics. At its core is a software composer — a complex algorithm that writes music in real-time, following the harmonic and mathematical rules embedded in it." },
      techIntro: "Key technologies:",
      tech: {
        markov: { title: "Markov chains:", description: "Used to create logical and harmonious sequences of notes and chords, ensuring the harmonic coherence of the music." },
        lsystems: { title: "L-systems and Mandelbrot fractals:", description: "These mathematical principles are used to develop the musical theme. Just as a complex tree grows from a small seed according to the program laid down in its DNA, a short initial musical phrase develops into a full-fledged, multifaceted composition. The generation rules determine how melodic lines, rhythmic patterns, and the interaction of instruments change." },
        engine: { title: "Evolution Engine:", description: "This is our special software engine that controls the entire process of music evolution. It ensures that the composition is constantly developing, while remaining harmonious and interesting to the listener." }
      }
    },
    howToUse: {
      title: "How to use? (Main controls)",
      intro: "The application interface is designed to be intuitive. Here are the main functions:",
      controls: {
        composition: { title: "Composition:", description: "The main working mode. Select a style, and the application will start generating music." },
        instruments: { title: "Instruments:", description: "A section where you can choose the instruments that will participate in the musical improvisation." },
        samples: { title: "Samples:", description: "Turn on/off and adjust the volume of additional sound textures like pads and sparkles." },
        mixer: { title: "Mixer (in each section):", description: "Allows you to adjust the volume of each instrument in the composition to achieve the perfect balance." }
      }
    }
  }
};

export type Dictionary = typeof dictionary;
